# Makefile

# File paths
YAML_FILE=quotes.yaml
GENERATED_FILE=quotes_data.go

# Generate the embedded Go file from quotes.yaml
.PHONY: quotes
quotes:
	@echo "Generating embedded Go file from $(YAML_FILE)..."
	@echo "// Code generated by Makefile; DO NOT EDIT." > $(GENERATED_FILE)
	@echo "//go:build !ignore_autogenerated" >> $(GENERATED_FILE)
	@echo "" >> $(GENERATED_FILE)
	@echo "package quotehub" >> $(GENERATED_FILE)
	@echo "" >> $(GENERATED_FILE)
	@echo "var quotesYAML = \`" >> $(GENERATED_FILE)
	@cat $(YAML_FILE) >> $(GENERATED_FILE)
	@echo "\`" >> $(GENERATED_FILE)
	@echo "Generated $(GENERATED_FILE)."
